#!/usr/bin/env bash

PS1=""
# TERMINAL PROMPT
# PS1="\[\e[0;93m\]\u\[\e[m\]"    # username
# PS1+=" "    # space
if [ $PS_STATE -eq 1 ]; then
    PS1+="\[\e[0;37m\]\$(projname)\[\e[m\]"    # current directory
    PS1+="\[\e[0;95m\]\W\[\e[m\]"    # current directory
    PS1+="\[\e[0;92m\]\$(git-branch)\[\e[m\]"    # current branch
fi

if [ $PS_STATE -eq 2 ]; then
    PS1+="\[\e[0;37m\]\$(projname)\[\e[m\]"    # current directory
    PS1+="\[\e[0;95m\].\[\e[m\]"    # current directory
    PS1+="\[\e[0;92m\]\$(git-branch)\[\e[m\]"    # current branch
fi

PS1+="$ "   # end prompt
export PS1;

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

ps0() {
    unset PROMPT_COMMAND
    PS_STATE=0
    source $DOTFILES_DIR/bash_prompt
}

ps1() {
    unset PROMPT_COMMAND
    PS_STATE=1
    source $DOTFILES_DIR/bash_prompt
}

ps2() {
    unset PROMPT_COMMAND
    PS_STATE=2
    source $DOTFILES_DIR/bash_prompt

}

# \e[0;30m = Dark Gray
# \e[1;30m = Bold Dark Gray
# \e[0;31m = Red
# \e[1;31m = Bold Red
# \e[0;32m = Green
# \e[1;32m = Bold Green
# \e[0;33m = Yellow
# \e[1;33m = Bold Yellow
# \e[0;34m = Blue
# \e[1;34m = Bold Blue
# \e[0;35m = Purple
# \e[1;35m = Bold Purple
# \e[0;36m = Turquoise
# \e[1;36m = Bold Turquoise
# \e[0;37m = Light Gray
# \e[1;37m = Bold Light Gra

# Special prompt variable characters:
#  \d   The date, in "Weekday Month Date" format (e.g., "Tue May 26"). 

#  \h   The hostname, up to the first . (e.g. deckard) 
#  \H   The hostname. (e.g. deckard.SS64.com)

#  \j   The number of jobs currently managed by the shell. 

#  \l   The basename of the shell's terminal device name. 

#  \s   The name of the shell, the basename of $0 (the portion following the final slash). 

#  \t   The time, in 24-hour HH:MM:SS format. 
#  \T   The time, in 12-hour HH:MM:SS format. 
#  \@   The time, in 12-hour am/pm format. 

#  \u   The username of the current user. 

#  \v   The version of Bash (e.g., 2.00) 

#  \V   The release of Bash, version + patchlevel (e.g., 2.00.0) 

#  \w   The current working directory. 
#  \W   The basename of $PWD. 

#  \!   The history number of this command. 
#  \#   The command number of this command. 

#  \$   If you are not root, inserts a "$"; if you are root, you get a "#"  (root uid = 0) 

#  \nnn   The character whose ASCII code is the octal value nnn. 

#  \n   A newline. 
#  \r   A carriage return. 
#  \e   An escape character (typically a color code). 
#  \a   A bell character.
#  \\   A backslash. 

#  \[   Begin a sequence of non-printing characters. (like color escape sequences). This
#       allows bash to calculate word wrapping correctly.

#  \]   End a sequence of non-printing characters.