#!/usr/bin/env bash

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# NAVIGATION
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../..'

# SOME MORE LS ALIASES
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias home='cd'
alias dow='cd ~/Downloads'
alias doc='cd ~/Documents'
alias dev='cd ~/dev'

# PYTHON VENV ALIASES
alias va='source ./$VENV/bin/activate'
alias da='deactivate'
alias makevenv='python -m venv .venv && va'
alias uppip='python -m pip install --upgrade pip'
alias pir='pip install -r '

# UTIL ALIASES
alias aliases="code $DOTFILES_DIR/aliases"
alias functions="code $DOTFILES_DIR/functions"
alias dotfiles="code -n $DOTFILES_DIR"
alias sand="cd $HOME/dev/sandbox_projects"
alias pysand="code -n $HOME/dev/sandbox_projects/pysandbox"
alias gitconfig="code $DOTFILES_DIR/gitconfig"
alias gitconfig_local="code .git/config"

# OTHER
alias path="tr ':' '\n' <<< \"$PATH\""

alias vba-parser="source ~/bin/open_vba_parser_proj.sh"

alias kport="source ~/bin/kill_port.sh"

# GET WEEK NUMBER
alias week='date +%V'
# GET UTC TIME
alias utc="date -u +'%H:%M:%S UTC'"

