#!/bin/bash

# NAVIGATION
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# SHORTHAND COMMANDS
alias l="ls -CF"
alias la="ls -lAh"
alias ll="ls -lh"
alias lh=ll
alias l.="ls -d .*"
alias la.="ls -lAh | awk '\$NF ~ /^\./'"
alias ll.=la.
alias rf="rm -rf"

# COMMON DIRECTORIES
alias dow="cd ~/Downloads"
alias dtop="cd ~/Desktop"
alias doc="cd ~/Documents"
alias home="cd"

alias p="cd $PROJECTS_DIR"
alias be="cd $BE_DIR"
alias mig="cd $MIGRATIONS_DIR"
alias q2c="cd $Q2C_DIR"
alias tests="cd $BE_DIR/tests/integration/src"
alias fe="cd $FE_DIR"
alias soa="cd $SOA_DIR"
alias sql="cd $PROJECTS_DIR/sql"

# PYTHON
alias da="deactivate"
alias pir="pip install -r"
alias uppip="python -m pip install --upgrade pip"

# SHOW/HIDE HIDDEN FILES
alias showhidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# MY SCRIPTS
alias kport="source ~/bin/kill_port.sh"
alias service="source ~/bin/start_service.sh"

# SCRIPTS EDITING
alias ed-services="$EDITOR $DOTFILES_DIR/services"
alias ed-aliases="$EDITOR $DOTFILES_DIR/aliases"
alias ed-functions="$EDITOR $DOTFILES_DIR/functions"
alias ed-envs="$EDITOR $DOTFILES_DIR/envs"
alias ed-paths="$EDITOR $DOTFILES_DIR/paths"
alias ed-dotfiles="$EDITOR -n $DOTFILES_DIR/"
alias ed-openscripts="$EDITOR ~/bin"
alias ed-scripts="$EDITOR ~/bin"
alias ed-bashprofile="$EDITOR $DOTFILES_DIR/.bash_profile"
alias ed-bashrc="$EDITOR $DOTFILES_DIR/.bashrc"

# PROJECTS EDITING
alias ed-be="$EDITOR -n $BE_DIR"
alias ed-mig="$EDITOR -n $MIGRATIONS_DIR"
alias ed-soa="$EDITOR -n $SOA_DIR"
alias ed-sql="$EDITOR -n $PROJECTS_DIR/sql"

# GIT
alias gitconfig="$EDITOR $DOTFILES_DIR/gitconfig"
alias gitconfig_local="$EDITOR ./.git/config"
alias wt-ls="wt-list"
alias wt-co="wt-checkout"
alias wt-mv="wt-move"
alias wt-rm="wt-remove"

# Chrono
alias week='date +%V'
alias utc="date -u +'%H:%M:%S UTC'"
alias short-date="date +%Y-%m-%d"
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

# Misc
alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'

alias cd="cdnvm"
alias path="tr ':' '\n' <<< \"$PATH\""

alias soapythonpath='export PYTHONPATH="$PYTHONPATH:$(pwd)/src"'
alias soaconfigfile="set -o allexport && source ./configs/envs/local.env && set +o allexport"
alias pysand="$EDITOR $PROJECTS_DIR/pysandbox"

alias expandalias="expand-alias"

alias add="git add --all"
alias addfiles="git add --"
alias push="git push"
alias rebase="git rebase"
alias pull="git pull"
alias fetch="git fetch --all"
alias addall="git add --all"
alias cam="git commit -am "
alias commit="git commit"
alias commitam="git commit -am"
alias stash="git stash"
alias status="git status"
alias statusv="git status -v"
alias s="git status"
alias sv="git status -v"
alias b="git branch"
alias cleanf="git clean -f"
alias checkout="git checkout"
alias co="git checkout"
alias curr-branch="git rev-parse --abbrev-ref HEAD"
alias undolast="git reset HEAD~1"
alias unstageall="git reset -- ."
alias recommit="commit -c ORIG_HEAD"
alias resethard="git reset HEAD --hard"
alias amend="git commit --amend"
alias commit-"noedit=git commit --amend --no-edit"
alias cnoe="git commit --amend --no-edit"
alias acnoe="git add --all && git commit --amend --no-edit"
alias pushrefs="git push origin HEAD:refs/for/master"
alias logv="git log"
alias lv="git log"
alias lg="git log --graph --pretty=format:'%C(yellow)%h%Creset %<(65,trunc)%s - %C(bold blue)%<(7,trunc)%an%Creset %C(bold red)%d %Creset%C(green)(%cr)' --abbrev-commit"
alias log="git log --graph --pretty=format:'%C(yellow)%h%Creset %<(65,trunc)%s - %C(bold blue)%<(7,trunc)%an%Creset %C(bold red)%d %Creset%C(green)(%cr)' --abbrev-commit"
alias lgstat="git log --graph --pretty=format:'%C(yellow)%h%Creset %<(65,trunc)%s - %C(bold blue)%<(7,trunc)%an%Creset %C(bold red)%d %Creset%C(green)(%cr)' --abbrev-commit --stat"
alias logstat="git log --graph --pretty=format:'%C(yellow)%h%Creset %<(65,trunc)%s - %C(bold blue)%<(7,trunc)%an%Creset %C(bold red)%d %Creset%C(green)(%cr)' --abbrev-commit --stat"
alias logsha="git log --pretty=format:'%H'"
alias lgsha="git log --pretty=format:'%H'"
alias sha="git log -1 --pretty=format:'%H'"
alias longsha="git log -1 --pretty=format:'%H'"
alias shortsha="git log -1 --pretty=format:'%h'"
alias wt="git worktree"
alias stat="git diff HEAD~1 HEAD --stat"
alias diff="git diff"
alias diffhead="git diff HEAD"

alias grep="grep --color=auto"
alias egrep="egrep --color=auto"