#!/bin/bash

# NAVIGATION
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# SHORTHAND COMMANDS
alias la="ls -lah"
alias ll="ls -lh"
alias rf="rm -rf"

# COMMON DIRECTORIES
alias dl="cd ~/Downloads"
alias dtop="cd ~/Desktop"
alias doc="cd ~/Documents"
alias home="cd ~"

alias p="cd ~/projects"
alias dev="cd ~/dev"
alias be="cd $BE_DIR"
alias cd-tests="cd tests/integration/src"
alias fe="cd $FE_DIR"
alias soa="cd $SOA_DIR"
alias myupdate="code -n ~/projects/my_update"

# PYTHON
alias da="deactivate"
alias rmvenv="da && rm -rf venv"
alias pir="pip install -r"
alias uppip="python -m pip install --upgrade pip"

# SHOW/HIDE HIDDEN FILES
alias showhidden="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# MY SCRIPTS
alias kport="source ~/bin/kill_port.sh"
alias service="source ~/bin/start_service.sh"

# EASIER SCRIPTS EDITING
alias services="code $DOTFILES_DIR/services"
alias aliases="code $DOTFILES_DIR/aliases"
alias functions="code $DOTFILES_DIR/functions"
alias exports="code $DOTFILES_DIR/exports"
alias paths="code $DOTFILES_DIR/paths"
alias dotfiles="code -n $DOTFILES_DIR/"
alias openscripts="code ~/bin"
alias scripts="code ~/bin"
alias bashprofile="code $DOTFILES_DIR/.bash_profile"
alias bashrc="code $DOTFILES_DIR/.bashrc"

# GIT
alias gitconfig="code $DOTFILES_DIR/gitconfig"
alias gitconfig_local="code ./.git/config"


# Get week number
alias week='date +%V'
# Get UTC time
alias utc="date -u +'%H:%M:%S UTC'"

# Google Chrome
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'

alias cd="cdnvm"
alias path="tr ':' '\n' <<< \"$PATH\""

alias soapythonpath='export PYTHONPATH="$PYTHONPATH:$(pwd)/src"'
