#!/usr/bin/env bash

# GIT FUNCTIONS
git_branch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

cob() {
    git checkout $(git branch | grep -i "$1")
}

findb() {
    git branch | grep -i "$1"
}

findwb() {
    git wb | grep -i "$1"
}

# nvm functions
cdnvm() {
    command cd "$@";
    nvm_path=$(nvm_find_up .nvmrc | tr -d '\n')

    # If there are no .nvmrc file, use the default nvm version
    if [[ ! $nvm_path = *[^[:space:]]* ]]; then

        declare default_version;
        default_version=$(nvm version default);

        # If there is no default version, set it to `node`
        # This will use the latest version on your machine
        if [[ $default_version == "N/A" ]]; then
            nvm alias default node;
            default_version=$(nvm version default);
        fi

        # If the current version is not the default version, set it to use the default version
        if [[ $(nvm current) != "$default_version" ]]; then
            nvm use default >/dev/null;
        fi

    elif [[ -s $nvm_path/.nvmrc && -r $nvm_path/.nvmrc ]]; then
        declare nvm_version
        nvm_version=$(<"$nvm_path"/.nvmrc)

        declare locally_resolved_nvm_version
        # `nvm ls` will check all locally-available versions
        # If there are multiple matching versions, take the latest one
        # Remove the `->` and `*` characters and spaces
        # `locally_resolved_nvm_version` will be `N/A` if no local versions are found
        locally_resolved_nvm_version=$(nvm ls --no-colors "$nvm_version" | tail -1 | tr -d '\->*' | tr -d '[:space:]')

        # If it is not already installed, install it
        # `nvm install` will implicitly use the newly-installed version
        if [[ "$locally_resolved_nvm_version" == "N/A" ]]; then
            nvm install "$nvm_version";
        elif [[ $(nvm current) != "$locally_resolved_nvm_version" ]]; then
            nvm use "$nvm_version" >/dev/null;
        fi
    fi
}

start-migrations() {
    if [ "$1" ]; then
        BRANCH_NAME="$1"
    else
        BRANCH_NAME=$(git branch --show-current)
    fi
    echo "Starting 'migrations' at '$BRANCH_NAME'..."
    cd "$HOME/projects/ggrc_be/$BRANCH_NAME/migrations"
    source $HOME/projects/ggrc_be/venv_migrations/bin/activate
    set -o allexport && source ./configs/envs/local.env && set +o allexport
    flask run --port=8088
}

start-be-db-init() {
    if [ "$1" ]; then
        BRANCH_NAME="$1"
    else
        BRANCH_NAME=$(git branch --show-current)
    fi
    echo "Starting 'be-db-init' at '$BRANCH_NAME'..."
    cd "$HOME/projects/ggrc_be/$BRANCH_NAME/migrations"
    source $HOME/projects/ggrc_be/venv_migrations/bin/activate
    ./scripts/db_init.sh
}

start-be() {
    if [ "$1" ]; then
        BRANCH_NAME="$1"
    else
        BRANCH_NAME=$(git branch --show-current)
    fi
    echo "Starting 'be' at '$BRANCH_NAME'..."
    cd "$HOME/projects/ggrc_be/$BRANCH_NAME"
    source $HOME/projects/ggrc_be/venv/bin/activate
    set -o allexport && source ./configs/envs/local.env && set +o allexport
    flask run --port=8082 --without-threads
}

start-fe-for-ui-tests() {
    echo "Starting 'fe' for ui tests..."
    cdnvm "$HOME/projects/ggrc_fe"
    npm run build:production -- --config=e2e && npm run serve -- --port=8081
}

start-fe() {
    echo "Starting 'fe'..."
    cdnvm "$HOME/projects/ggrc_fe"
    npm run dev
}

start-soa() {
    echo "Starting 'soa service'..."
    cdnvm "$HOME/projects/soa"
    source ./venv/bin/activate
    set -o allexport && source ./configs/envs/local.env && set +o allexport
    cd src 
    flask run --port=9090 --without-threads
}

start-soa-db-reset() {
    echo "Starting 'soa db reset'..."
    cdnvm "$HOME/projects/soa"
    source ./venv/bin/activate
    export PYTHONPATH="$PYTHONPATH:$(pwd)/src"
    ./bin/db_reset
}

start-q2c() {
    echo "Starting 'q2c'..."
    cd "$HOME/projects/q2c"
    source ./venv/bin/activate
    ./bin/run_local.py
}

expand-alias() {
    if [ -z "$1" ]; then
        echo "Missing alias name"
        return
    fi
    alias "$@" | cut -d\' -f2
}

patchset() {
    grep 'patchset' .branch_info | cut -d\= -f2
}

wt() {
    git worktree "$@"
}

va() {
    if [ $# -eq 0 ]
      then
        source venv/bin/activate
        return
    fi

    case "$1" in 
        be)
            va-be
            ;;
        migration | migrations)
            va-migrations
            ;;
        *)
            echo "Unknown venv!"
            ;;
    esac
}

va-migrations(){
    source $BE_DIR/venv_migrations/bin/activate
}

va-be(){
    source $BE_DIR/venv/bin/activate
}

wt() {
    git worktree "$@"
}

wt-add() {
    if [ $# -eq 0 ]
      then
        echo "git worktree add -b <branch> <path> <commit-ish>"
        return
    fi

    git worktree add "$@"
}

# tmux attach
function tat {

# When starting work on a project: open the terminal, cd into the folder, then `tat`.
#
# This function:
#
# - gets the name of the current directory and removes periods, which tmux doesn't like.
# - if any session with the same name is open, it re-attaches to it.
# - otherwise, it checks if an .envrc file is present and starts a new tmux session using direnv exec.
# - otherwise, starts a new tmux session with that name.
 
  name=$(basename `pwd` | sed -e 's/\.//g')

  if tmux ls 2>&1 | grep "$name"; then
    tmux attach -t "$name"
  elif [ -f .envrc ]; then
    direnv exec / tmux new-session -s "$name"
  else
    tmux new-session -s "$name"
  fi
}