#!/usr/bin/env bash

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# PARENT DIR NAVIGATION
alias ..="pushd .."
alias ...="pushd ../.."
alias ....="pushd ../../.."
alias pd="pushd"
alias pp="popd"

# PYTHON VENV ALIASES
alias da="deactivate"
alias makevenv="python -m venv $TT_VENV_DIR && va"
alias uppip="python -m pip install --upgrade pip"
alias pir="pip install -r "

# UTIL ALIASES
alias pathtr="tr ':' '\n' <<< \"$PATH\""
alias kport="source ~/bin/kill_port.sh"
alias expandalias="expand-alias"

# DATETIME
alias week='date +%V'
alias utc="date -u +'%H:%M:%S UTC'"

# NAVIGATE ALIASES
alias home="pushd ~"
alias dow="pushd ~/Downloads"
alias doc="pushd ~/Documents"
alias vid="pushd ~/Videos"
alias p="pushd $TT_PROJECTS_DIR"

alias dot="pushd $TT_DOTFILES_DIR"
alias sand="pushd $TT_PROJECTS_DIR/sandbox_projects"

alias cdp="cd $TT_PROJECTS_DIR"
alias cddot="cd $TT_DOTFILES_DIR"
alias cddow="cd ~/Downloads"
alias cddoc="cd ~/Documents"
alias cdvid="cd ~/Videos"

alias cls="clear"

# OPEN WITH TT_EDITOR
alias ed-history="$TT_EDITOR $HOME/.bash_history"
alias ed-gitignore_global="$TT_EDITOR $DEVSETU_DIR/gitignore_global"
alias ed-dot="$TT_EDITOR -n $TT_DOTFILES_DIR"
alias ed-fish="$TT_EDITOR -n $XDG_CONFIG_HOME/fish"

# WORKTREE FUNCTIONS
alias gwt-ls="gwt-list"
alias gwt-co="gwt-checkout"
alias gwt-rm="gwt-remove"
alias gwt-mv="gwt-move"
