#!/usr/bin/env bash

ps0() {
  unset PROMPT_COMMAND
  PS1='$ '
}

ps1() {
    source $TT_DOTFILES_OS_DIR/bash/prompt
}

# Get named var (usage: get "VAR_NAME")
get() {
  echo "${!1}"
}

# git functions
git-branch() {
  git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

git-init() {
  git init
  git config --local user.name "stanislavsabev"
  git config --local user.email "bezraboten.34@gmail.com"
}


cob () {
  git checkout $(git branch | grep -i "$1")
}

findb() {
  git branch | grep -i "$1"
}

ls-dotfiles() {
  find . -maxdepth 1 -name ".*" -type l,f
}

ls-dotdirs() {
  find . -maxdepth 1 -name ".*" -type d
}

# tmux attach
tat() {

  # When starting work on a project: open the terminal, cd into the folder, then `tat`.
  #
  # This function:
  #
  # - gets the name of the current directory and removes periods, which tmux doesn't like.
  # - if any session with the same name is open, it re-attaches to it.
  # - otherwise, it checks if an .envrc file is present and starts a new tmux session using direnv exec.
  # - otherwise, starts a new tmux session with that name.
  
    name=$(basename `pwd` | sed -e 's/\.//g')

    if tmux ls 2>&1 | grep "$name"; then
      tmux attach -t "$name"
    elif [ -f .envrc ]; then
      direnv exec / tmux new-session -s "$name"
    else
      tmux new-session -s "$name"
    fi
}


patchset() {
    grep 'patchset' .branch_info | cut -d\= -f2
}


va() {
    local VA_NAME=
    if [ $# -gt 0 ] && [ $1 == "--help" ] || [ $1 == "-h" ]; then
        usage="usage: va [VENV_PATH]
    If no VENV_PATH is provided, activates the default venv at $TT_VENV_DIR
    "
        echo "$usage"
        return
    fi

    if [ $# -eq 0 ]; then
      VA_NAME="$TT_VENV_DIR"
    else
      VA_NAME="$1"
    fi
    source "$VA_NAME/bin/activate"
}


gwt() {
    if [ $# -eq 0 ] || [ $1 == "--help" ] || [ $1 == "-h" ]; then
        usage="usage: [-h] [COMMAND]
    Call worktree command
    
    -h --help   Print this message

    COMMANDS
        a | add 
       co | checkout 
       ls | list  
       mv | move 
       rm | remove
    clone | 
    "
        echo "$usage"
        return
    fi
    if [ $1 == "a" ] || [ $1 == "add" ]; then
        gwt-add "${@:2}"
        return
    elif [ $1 == "co" ] || [ $1 == "checkout" ]; then
        gwt-checkout "${@:2}"
        return
    elif [ $1 == "ls" ] || [ $1 == "list" ]; then
        gwt-list "${@:2}"
        return
    elif [ $1 == "mv" ] || [ $1 == "move" ]; then
        gwt-move "${@:2}"
        return
    elif [ $1 == "rm" ] || [ $1 == "remove" ]; then
        gwt-remove "${@:2}"
        return
    elif [ $1 == "clone" ]; then
        gwt-clone "${@:2}"
        return
    else
        echo "gwt: unknown command $1"
        return 1
    fi
    return
    git worktree "$@"
}

gwt-add() {
    if [ $# -eq 0 ] || [ $1 == "--help" ] || [ $1 == "-h" ]; then
        echo "usage: gwt-add [-h] <worktree> [path=worktree] <commit-ish>"
        return
    fi
    if [ $1 == "--dry-run" ] || [ $1 == "-n" ]; then
        DRY_RUN=1
        shift
    else
        DRY_RUN=0
    fi

    case $# in
        1)
            set -- "$1" "$1"
            ;;
        2)
            set -- -b "$1" "$1" "$2"
            ;;
        3)
            set -- -b "$1" "$2" "$3"
            ;;
        *)
            echo "gwt-add: invalid number of arguments, see -h for usage"
            return 1
            ;;
    esac

    # -b <branch-name> <path-name> <commit-ish>
    local cmd="git worktree add"
    if [ "$DRY_RUN" -eq 1 ]; then
        echo "[DRY-RUN] $cmd" "$@"
    else
        echo "$cmd" "$@"
        # eval "$cmd" "$@"
    fi
    
}

gwt-checkout() {
    echo "gwt-checkout <worktree(==branch-name)> NOT IMPLEMENTED"
}

gwt-list() {
    git worktree list "$@"
}

gwt-move() {
    git worktree move "$1" "$2"
    cd "$2"
    git branch -M "$2"
    cd - 
}

gwt-remove() {
    if [ $# -eq 0 ]; then
        echo "git worktree remove <worktree(==branch-name)> [--force]"
        return
    fi

    local WHERE="$1"
    if [[ $WHERE == */ ]]; then
        WHERE=${WHERE::-1}
    fi
    echo $WHERE
    shift
    
    if [[ "$1" == "--force" ]]; then
        git worktree remove --force $WHERE && git branch -D $WHERE
    else
        git worktree remove $WHERE && git branch -D $WHERE
    fi
}

gcert() {
  if [[ -n $TMUX ]]; then
    eval $(tmux show-environment -s)
  fi

  command gcert "$@"
}

glogin() {
  if [[ -n $TMUX ]]; then
    eval $(tmux show-environment -s)
  fi

  command glogin "$@"
}

gcertstatus() {
  if [[ -n $TMUX ]]; then
    eval $(tmux show-environment -s)
  fi

  command gcertstatus "$@"
}
