#!/usr/bin/env bash

# VSCODE FUNCTIONS

vscode-add-sett () {
    # if [ ! -d ".vscode" ]; then
    #     mkdir .vscode
    # fi
    cp -Raf ../.ignore/.vscode/ .vscode/
}

vscode-clear-cache() {
    rm -rf ~/Library/Application\ Support/Code/Cache/*
    rm -rf ~/Library/Application\ Support/Code/CachedData/*
}

vscode-clear-pycache() {
    find . -name "*.pyc" -delete
    find . -name "__pycache__" -type d -exec rm -rf {} +
    find . -name ".pytest_cache" -type d -exec rm -rf {} +
}